### ISSUE TITLE
Explicit port 80 gets lost for http proxies

### ISSUE THREAD

**Issue by kinnison** [inejge/env_proxy#6]
Hi,

A user of `rustup` came to us yesterday with an issue they have.  Their corporate web proxy runs on port 80, not port 8080 and they cannot use `rustup` via our `env_proxy` support (forcing them to fall back to cURL mode).

As an example, I wrote a trivial echo-proxy program:

```rust
fn main() {
    println!("{:?}", env_proxy::for_url(&url::Url::parse("http://www.example.org").unwrap()).to_url());
}
```

If you run it as:
```console
$ env http_proxy=http://corporate-proxy:80 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/echoproxy`
Some("http://corporate-proxy:8080/")
$
```

You can see that the explicit `:80` on the proxy variable has been eaten somewhere along the way.

I believe I have traced this through `env_proxy::ProxyUrl::to_url()` through its use of `url.port().is_some()` (which seems reasonable) into `url::parser::Parser::parse_port()` where it has:

```rust
if !has_any_digit || opt_port == default_port() {
            opt_port = None;
}
```

This means that if a URL has an explicit `:PORTNR` where that matches the default port number for the scheme in question (`http` and `:80` here) then it claims the incoming URL had no port number.  As such your approach to detecting the port is not going to always work.

As I see it there are two options here:

1. An alternative, more explicitly preserving-of-form URL parser is used
2. A change to `url` is proposed in which the port (if present) is always recorded, and then perhaps not serialised back out if it's not needed.

Either way, right now this is blocking some `rustup` users from being able to use `env_proxy` and `reqwest` because of their corporate proxies using port 80 :(

**Comment by inejge** [comment]
@kinnison Nice analysis. While running a proxy on port 80 is... eccentric, it should be supported. The root of the problem is that a proxy URL uses the `http` scheme, but its default port is 1080 (cURL) or 8080 (`env_proxy`), instead of 80, and there is no way to tell that to `Url::parse()`. I know how I'd change `url`, and I'll propose the change by and by, but meanwhile I believe that I can patch `env_proxy` to sidestep the problem.

**Comment by inejge** [comment]
Ok, you can try the "explicit80" branch.

**Comment by kinnison** [comment]
Okay, running that through my echo proxy test confirms that it works.

I am _uncomfortable_ with the use of `unsafe` and while I understand the efficiency argument, I wonder if it might be better to have `ProxyUrl` carry an `Option<String>` for the scheme which should be used, and then unconditionally replace the scheme in the stored URL when it's set into `ProxyUrl` ? If you have a better discussion ongoing with `url`'s upstream then ignore me :D

If you can make a release in which this functionality (in whatever form) is present, I'll udpate rustup for it.

*thank you*

**Comment by inejge** [comment]
I lost the `unsafe` and 0.3.1 will be up on crates.io shortly.

**Comment by kinnison** [comment]
Awesome, thank you so much @inejge -- I shall update rustup tonight and ask the original bug reporter to check.

**Comment by kinnison** [comment]
Confirmed as good by the bug reporter, thank you!
